export const recetasCaribe = [
  {
    id: '1',
    nombre: 'Arepa de Huevo',
    descripcion: 'La arepa de huevo es un clásico de la gastronomía costeña de Colombia. Se trata de una arepa frita rellena de huevo, crujiente por fuera y suave por dentro. Es un desayuno tradicional en ciudades como Cartagena y Barranquilla, y se disfruta mejor recién hecha y acompañada de café o jugo natural.',
    ingredientes: 'Harina de maíz, Huevo, Sal, Aceite para freír',
    ubicacion: 'Cartagena, Bolívar',
    region: 'Caribe',
    tiempoPreparacion: '30 minutos',
    porciones: 2,                          
    pasos: [                               
      'Mezclar la harina con agua y sal',
      'Formar las arepas y freír ligeramente',
      'Rellenar con huevo y freír hasta dorar',
    ],
    imagen: require('../assets/imagenesCaribe/arepa-huevo.jpg'),
  },
  {
    id: '2',
    nombre: 'Mote de Queso',
    descripcion: 'El mote de queso es un plato típico de la costa caribe colombiana, especialmente de Sucre y Córdoba. Se prepara con ñame cocido y queso costeño, y se sirve como desayuno o acompañamiento. Su sabor combina la suavidad del ñame con la salinidad del queso, creando una experiencia única y reconfortante.',
    ingredientes: 'Ñame, Queso costeño, Cebolla, Ajo, Achiote',
    ubicacion: 'Sincelejo, Sucre',
    region: 'Caribe',
    tiempoPreparacion: '45 minutos',
    porciones: 4,
    pasos: [
     'Cocer el ñame hasta que esté blando',
      'Preparar el sofrito con cebolla, ajo y achiote',
      'Mezclar el ñame con el queso y el sofrito',
      'Servir caliente',
    ],
    imagen: require('../assets/imagenesCaribe/mote-de-queso.jpg'),
  },
  {
    id: '3',
    nombre: 'Arroz con Coco',
    descripcion: 'El arroz con coco es un plato emblemático de la costa caribe colombiana, caracterizado por su sabor dulce y cremoso gracias a la leche de coco. Se sirve tradicionalmente como acompañante de pescados o mariscos, y es muy apreciado en festividades y reuniones familiares.',
    ingredientes: 'Arroz, Coco rallado, Azúcar, Sal, Aceite',
    ubicacion: 'Santa Marta, Magdalena',
    region: 'Caribe',
    tiempoPreparacion: '40 minutos',
    porciones: 4,
    pasos: [
      'Lavar el arroz y escurrirlo',
      'En una olla, calentar el aceite y añadir el arroz',
      'Agregar leche de coco, agua, azúcar y sal',
      'Cocinar a fuego bajo hasta que el arroz esté tierno',
      'Servir caliente',
    ],
    imagen: require('../assets/imagenesCaribe/arroz-coco.jpg'),
  },
  {
    id: '4',
    nombre: 'Cazuela de Mariscos',
    descripcion: 'La cazuela de mariscos es una sopa cremosa y nutritiva típica del Caribe colombiano. Combina la frescura de los mariscos locales con el sabor suave y dulce de la leche de coco, creando un plato ideal para disfrutar en familia o en celebraciones especiales.',
    ubicacion: 'Barranquilla, Atlántico',
    ingredientes: 'Camarones, Calamares, Mejillones, Leche de coco, Verduras',
    region: 'Caribe',
    tiempoPreparacion: '50 minutos',
    porciones: 4,
    pasos: [
      'Lavar y limpiar los mariscos',
      'Preparar un sofrito con cebolla, ajo y verduras',
      'Agregar los mariscos y leche de coco',
      'Cocinar a fuego medio hasta que los mariscos estén listos',
      'Servir caliente acompañado de arroz blanco',
    ],
    imagen: require('../assets/imagenesCaribe/cazuela-mariscos.jpg'),
  },
  {
    id: '5',
    nombre: 'Sancocho de Pescado',
    descripcion: 'El sancocho de pescado es una sopa tradicional de la región caribeña, elaborada con pescado fresco y tubérculos autóctonos como yuca y plátano. Es un plato lleno de sabor y tradición, ideal para compartir en familia y disfrutar de la gastronomía costeña.',
    ingredientes: 'Pescado, Yuca, Plátano, Mazorca, Cilantro, Cebolla',
    ubicacion: 'San Andrés Islas',
    region: 'Caribe',
    tiempoPreparacion: '60 minutos',
    porciones: 6,
    pasos: [
      'Limpiar y cortar el pescado en porciones',
      'Pelar y cortar los tubérculos y plátano',
      'Hacer un sofrito con cebolla y ajo',
      'Agregar agua, tubérculos y pescado',
      'Cocinar hasta que todo esté tierno y sazonar con cilantro',
    ],
    imagen: require('../assets/imagenesCaribe/sancocho-de-pescado.jpg'),
  },
];